apiVersion: apps/v1
kind: Deployment
metadata:
        name: web
spec:
        replicas: 2
        template:
                spec:
                        containers:
                                - name: web
                                  image: quay.io/rdrysdal/web:v1
                                  ports:
                                          - containerPort: 5000

