
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tail-spin-environments 
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/lijcam/tailspin-argocd-cd
    targetRevision: restructure
    path: ./doc/OpenShift/apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc

