# Development application environment

---
apiVersion: v1
kind: Namespace
metadata:
  name: tail-spin-development
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops


# Production application environment

---
apiVersion: v1
kind: Namespace
metadata:
  name: tail-spin-production
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tail-spin-environments 
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/lijcam/tailspin-argocd-cd
    targetRevision: restructure
    path: ./docs/OpenShift/app
  destination:
    namespace: default
    server: https://kubernetes.default.svc

